spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentDB?createDatabaseIfNotExist=true
    username: postgres
    password: qwer
    driver-class-name: com.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
